# Generated by Django 4.2.1 on 2023-06-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=150, verbose_name='заголовок')),
                ('slug', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='содержимое')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='создан')),
                ('publication_flag', models.BooleanField(default=True, verbose_name='публикация')),
                ('count_views', models.IntegerField(default=0, verbose_name='кол-во просмотров')),
            ],
            options={
                'verbose_name': 'публикация',
                'verbose_name_plural': 'публикации',
                'ordering': ('heading',),
            },
        ),
    ]
